// Reproducciones de auditoría: assertan el defecto existente, NO son tests de aceptación.
// Sin red ni BD real. El SDK y todas las escrituras están simulados.
require('reflect-metadata');const assert=require('node:assert/strict'),fs=require('fs');
let modelo={stop_reason:'end_turn',content:[],usage:{}};
const sdk=require.resolve('@anthropic-ai/sdk');require.cache[sdk]={id:sdk,filename:sdk,loaded:true,exports:class {constructor(){this.messages={create:async()=>modelo,stream:()=>({finalMessage:async()=>modelo})};}}};
process.env.ANTHROPIC_API_KEY='mock';
const {AuthGuard}=require('../dist/auth/auth.guard'),{Reflector}=require('@nestjs/core');
const {ComprasService}=require('../dist/compras/compras.service'),{ComprasController}=require('../dist/compras/compras.controller');
const {RepartosService}=require('../dist/repartos/repartos.service'),{CajaService}=require('../dist/caja/caja.service');
const {ListasService}=require('../dist/listas/listas.service'),{AgenteService}=require('../dist/agente/agente.service');
const {ejecutarHerramienta}=require('../dist/agente/herramientas');
const {ClientesAuthService}=require('../dist/clientes-auth/clientes-auth.service');
const {PedidosService}=require('../dist/pedidos/pedidos.service');
function db(tablas={},hook){const writes=[],queries=[],rpcCalls=[];return {writes,queries,rpcCalls,auth:{admin:{createUser:async()=>({error:null})}},storage:{from:()=>({upload:async()=>({error:null}),createSignedUrl:async()=>({data:{signedUrl:'mock'}})})},rpc:async(n,a)=>(rpcCalls.push({n,a}),{data:null,error:null}),from(t){const r=tablas[t]??{data:null,error:null};const q={table:t,filters:[]};queries.push(q);const b={};for(const k of ['select','eq','neq','is','not','in','gte','gt','lte','lt','ilike','limit','order','range','or'])b[k]=(...a)=>(q.filters.push([k,...a]),b);for(const k of ['insert','update','upsert','delete'])b[k]=fila=>{writes.push({table:t,op:k,fila});hook?.(t,k,fila);return b};b.single=b.maybeSingle=async()=>r;b.then=(ok,err)=>Promise.resolve(r).then(ok,err);return b;}};}
const results=[];async function run(id,fn){try{const evidence=await fn();results.push({id,reproducido:true,evidence});}catch(e){results.push({id,reproducido:false,error:e.message});}}
(async()=>{
 await run('S01',async()=>{const jwt={verifyAsync:async()=>({sub:'usuario-desactivado',rol:'dueno'})};const g=new AuthGuard(jwt,new Reflector());const req={headers:{authorization:'Bearer simulada'}};const h=()=>{};Reflect.defineMetadata('roles',['dueno'],h);assert.equal(await g.canActivate({getHandler:()=>h,getClass:()=>class{},switchToHttp:()=>({getRequest:()=>req})}),true);return 'Token emitido antes de una desactivación sigue autorizado; el guard no consulta usuario activo ni revocación';});
 await run('S02',async()=>{const g=new AuthGuard({verifyAsync:async()=>({sub:'cliente-A',rol:'cliente'})},new Reflector());const req={headers:{authorization:'Bearer simulada'}};assert.equal(await g.canActivate({getHandler:()=>ComprasController.prototype.estadoEntradaFoto,getClass:()=>ComprasController,switchToHttp:()=>({getRequest:()=>req})}),true);const d=db({lecturas_comprobante:{data:{estado:'listo',resultado:{proveedor:{nombre:'Proveedor interno'}}}}});const s=new ListasService(d);s.actualizarLectura=async x=>x;assert.equal((await s.estadoLecturaComprobante('lectura-de-otro')).proveedor.nombre,'Proveedor interno');return 'Cliente obtiene resultado de lectura de compras por ID; sin rol ni propietario';});
 await run('S03',async()=>{const d=db({sesiones_caja:{data:{id:'caja-B',empleado_id:'empleado-B',cerrada_en:null}},caja_movimientos:{data:{id:'mov'}}});await new CajaService(d,{}).registrarMovimiento({sesionId:'caja-B',tipo:'egreso',monto:100,motivo:'prueba'},'empleado-A');assert.equal(d.writes[0].fila.sesion_id,'caja-B');return 'Cajero A registra retiro de efectivo en caja B sin verificar asignación';});
 await run('S04',async()=>{const d=db();await new PedidosService(d,{}).repartidorUbicacion('pedido-de-otro',-34,-58);assert.equal(d.writes[0].table,'pedidos');return 'Ubicación de pedido ajeno se actualiza por ID sin repartidor asignado';});
 await run('S05',async()=>{let estado='en_calle';const d=db({clientes:{data:[{id:'c',cta_cte_habilitada:true}]}},(t,k,f)=>{if(t==='repartos'&&k==='update')estado=f.estado;});const s=new RepartosService(d);s.detalle=async()=>({id:'r',numero:10,estado,paradas:[{cliente_id:'c',estado:'entregado',monto:100,cobrado:0}],totales:{estimado:100,cobrado:0,efectivo:0}});await s.cambiarEstado('r','rendido','a');await s.cambiarEstado('r','armado','a');await s.cambiarEstado('r','rendido','a');assert.equal(d.writes.filter(x=>x.table==='cuenta_corriente').length,2);return 'Rendido → armado → rendido duplica deuda';});
 await run('S06',async()=>{const d=db({clientes:{data:[{id:'c',cta_cte_habilitada:true}]}});const s=new RepartosService(d);s.detalle=async()=>({id:'r',numero:10,estado:'en_calle',paradas:[{cliente_id:'c',estado:'entregado',monto:100,cobrado:50}],totales:{estimado:100,cobrado:50,efectivo:50}});await Promise.all([s.cambiarEstado('r','rendido','a'),s.cambiarEstado('r','rendido','b')]);assert.equal(d.writes.filter(x=>x.table==='cuenta_corriente').length,2);assert.equal(d.writes.filter(x=>x.table==='cobranzas_pendientes').length,2);return 'Dos rendiciones concurrentes generan dos deudas y dos cobros';});
 await run('S07',async()=>{const d=db({ordenes_pago_items:{data:[{factura_id:'f'}]},ordenes_pago:{data:{estado:'pagada'}}});const r=await new ComprasService(d).rechazarOrdenPago('op-pagada',{usuarioId:'u'});assert.equal(r.rechazada,true);assert.equal(d.writes[0].fila.estado,'rechazada');return 'Se rechaza OP pagada y se reabren facturas sin validar estado anterior';});
 await run('S08',async()=>{const d=db({facturas_proveedor:{data:{id:'f'}}});const r=await new ComprasService(d).registrarFactura({proveedorId:'p',numero:'TEST',monto:100,neto:1000,iva:210,pagada:true},'comprador');assert.equal(r.ok,true);assert.equal(d.writes[0].fila.monto_pagado,100);return 'Registro acepta total 100 con neto 1000 + IVA 210 y pagada=true sin pago/OP';});
 await run('S09',async()=>{const d=db({facturas_proveedor:{data:{id:'f'}},facturas_proveedor_items:{error:{message:'fallo de escritura'}}});const r=await new ComprasService(d).registrarFactura({proveedorId:'p',numero:'TEST',monto:100,items:[{descripcion:'Agua',cantidad:1,precio:100}]},'u');assert.equal(r.ok,true);return 'Falla de inserción de renglones deja encabezado y devuelve ok';});
 await run('S10',async()=>{const d=db();const r=await ejecutarHerramienta(d,'notify_admin',{titulo:'Alerta',mensaje:'Falta dato'});assert.equal(r.resultado.notificado,true);assert.equal(d.writes.length,0);return 'notify_admin confirma notificación sin persistirla ni enviarla';});
 await run('S11',async()=>{modelo={stop_reason:'tool_use',content:[{type:'tool_use',id:'1',name:'request_human_review',input:{motivo:'alto impacto'}},{type:'tool_use',id:'2',name:'update_stock',input:{sku:'A',cantidad:12}}]};const d=db({agente_tareas:{data:{id:1,descripcion:'Prueba',estado:'pendiente'}},productos:{data:{id:'p'}}});const r=await new AgenteService(d).ejecutar(1);assert.equal(r.estado,'escalada');assert.equal(d.rpcCalls.filter(x=>x.n==='registrar_movimiento').length,1);return 'Tras escalar, otra herramienta del mismo turno modifica stock';});
 await run('S12',async()=>{modelo={stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify({proveedor:{nombre:'Prueba'},items:[{descripcion:'Agua mineral',cantidad:2,precio:100,importe:null}],impuestos:{total:200},dudas:[]})}],usage:{}};const d=db({proveedores:{data:[]}});const s=new ListasService(d);s.validarPie=()=>false;s.sugerirMatchConIA=async()=>new Map();const r=await s.analizarComprobanteFoto({buffer:Buffer.from('mock'),mimetype:'image/jpeg'});assert.equal(r.items[0].importe,0);return {importeLeido:null,importeProcesado:r.items[0].importe,interpretado:r.items[0].interpretado};});
 await run('S13',async()=>{const d=db({clientes:{data:{id:'cliente-existente'}}});const s=new ClientesAuthService(d,{});s.loginEmail=async()=>({token:'mock'});await s.registroEmail('tercero@example.test','Nombre cambiado','abcdef');assert.equal(d.writes[0].fila.nombre,'Nombre cambiado');return 'Email autoconfirmado sin verificar propiedad permite vincular ficha comercial existente';});
 await run('S14',async()=>{const d=db();await new RepartosService(d).marcarParada('parada-ajena',{estado:'entregado',cobrado:-100});assert.equal(d.writes[0].fila.cobrado,-100);return 'Parada ajena acepta cobro negativo sin actor ni validación de monto';});
 await run('S15',async()=>{const d=db({facturas_proveedor:{data:{id:'f'}}});const r=await new ComprasService(d).registrarFactura({proveedorId:'p',numero:'TEST',monto:100,items:[{descripcion:'Agua',cantidad:0,precio:100}]},'u');assert.equal(r.ok,true);assert.equal(d.writes.find(x=>x.table==='facturas_proveedor_items').fila[0].cantidad,1);return 'Renglón de factura con cantidad 0 se guarda como 1';});
 await run('S16',async()=>{const ts=require('typescript'),vm=require('node:vm');const js=ts.transpileModule(fs.readFileSync('../mobile/src/lib/api.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;let expulsado=0;const ctx={exports:{},require:()=>({API:'http://mock'}),AbortController,setTimeout,clearTimeout,fetch:async()=>({status:403,ok:false,text:async()=>'{"message":"Necesitás verificarte"}'})};vm.runInNewContext(js,ctx);ctx.exports.configurarApi({getToken:()=> 'valido',onUnauthorized:()=>expulsado++});await ctx.exports.api('/app/compra-facil').catch(()=>{});assert.equal(expulsado,1);return '403 por falta de permisos se interpreta como sesión expirada y expulsa al cliente';});
 await run('S17',async()=>{modelo={stop_reason:'tool_use',content:[{type:'tool_use',id:'x',name:'update_stock',input:{sku:'INEXISTENTE',cantidad:1}}]};const d=db({agente_tareas:{data:{id:1,descripcion:'Prueba',estado:'pendiente'}}});const r=await new AgenteService(d).ejecutar(1);assert.equal(r.estado,'completada');assert.equal(d.writes.filter(w=>w.table==='agente_auditoria'&&w.fila.ok===false).length,6);return 'Agente falla sus seis herramientas y marca tarea completada';});
 await run('S18',async()=>{const {ChequesService}=require('../dist/cheques/cheques.service');const d=db({cheques:{data:{id:'ch',estado:'depositado',tipo:'terceros',cliente_id:'c',importe:100}}});const s=new ChequesService(d);await Promise.all([s.rechazar('ch',{}),s.rechazar('ch',{})]);assert.equal(d.writes.filter(w=>w.table==='cuenta_corriente').length,2);return 'Rechazos simultáneos de un cheque pueden duplicar débito de cliente';});
 await run('S19',async()=>{const {MercadoPagoController}=require('../dist/mercadopago/mercadopago.controller');let input;await new MercadoPagoController({iniciarCobroQR:async x=>(input=x)}).cobroQR({cajaId:'caja',monto:1},{usuario:{sub:'cajero'}});assert.equal(input.usuarioId,undefined);return 'Controller QR lee req.user pero AuthGuard escribe req.usuario: pierde autor';});
 await run('S20',async()=>{process.env.MERCADOPAGO_ACCESS_TOKEN='mock';delete process.env.MERCADOPAGO_WEBHOOK_SECRET;const prev=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({status:'approved',external_reference:'pedido-1000',transaction_amount:1,currency_id:'USD'})});try{const d=db();await new PedidosService(d,{}).webhookMP({type:'payment',data:{id:'test'}},{});assert.equal(d.writes.length,2);assert.ok(d.writes[0].fila.pagado_en);return 'Pago aprobado de $1 USD marca pagado un ID de pedido sin consultar total ni moneda (firma excluida del test; producción sí la exige)';}finally{global.fetch=prev;}});
 await run('S21',async()=>{const prev=global.fetch;global.fetch=async()=>{throw Error('fallo temporal MP')};try{const r=await new PedidosService(db(),{}).webhookMP({type:'payment',data:{id:'test'}},{});assert.equal(r.ok,true);return 'Fallo temporal al consultar MP se acusa ok; se pierde incentivo de reintento del webhook';}finally{global.fetch=prev;}});
 await run('S22',async()=>{const ws=require('../dist/caja/arca-wsaa');ws.emisorConfigurado=()=>true;const {ArcaService}=require('../dist/caja/arca.service');const d=db({comprobantes_arca:{data:[{id:'a',tipo:'FA',punto_venta:1,venta:{sucursal:{arca_emisor:'principal'}}},{id:'b',tipo:'FA',punto_venta:1,venta:{sucursal:{arca_emisor:'santa_ines'}}}]}});const s=new ArcaService(d);s.estaConfigurado=()=>true;s.authXml=async x=>x;const consultas=[];s.ultimoAutorizado=async emisor=>(consultas.push(emisor),emisor==='principal'?100:900);const emitidos=[];s.emitirUno=async(a,c,t,n)=>(emitidos.push({emisor:a,n}),{cae:'mock',vencimiento:'2026-10-01'});await s.emitirPendientes();assert.deepEqual(consultas,['principal']);assert.equal(emitidos[1].n,102);return {esperadoSegundoEmisor:901,numeroUsado:emitidos[1].n,causa:'Cache por punto de venta/tipo omite emisor'};});
 await run('S23',async()=>{const {ArcaService}=require('../dist/caja/arca.service');const d=db({comprobantes_arca:{data:[{id:'a',tipo:'FA',punto_venta:1,venta:{sucursal:{arca_emisor:'principal'}}}],error:null}});const original=d.from.bind(d);d.from=t=>{const b=original(t);const old=b.update;b.update=x=>{old(x);b.then=(ok,err)=>Promise.resolve({data:null,error:{message:'falló persistencia CAE'}}).then(ok,err);return b;};return b;};const s=new ArcaService(d);s.estaConfigurado=()=>true;s.authXml=async()=> 'mock';s.ultimoAutorizado=async()=>100;s.emitirUno=async()=>({cae:'mock',vencimiento:'2026-10-01'});const r=await s.emitirPendientes();assert.equal(r.emitidos,1);assert.equal(r.errores,0);return 'CAE autorizado por servicio simulado y falla de guardado local igualmente devuelven emitido, sin error';});
 await run('S24',async()=>{const cuentas=require('../dist/mercadopago/mp-cuentas');cuentas.cuentaDeSucursal=async()=>({token:'mock',slug:'principal'});const {CompraFacilService}=require('../dist/comprafacil/comprafacil.service');const d=db({clientes:{data:{id:'c',verificado:true,tipo:'habitual'}},productos:{data:{id:'p',nombre:'Queso por kg'}},compra_facil_pendientes:{data:{id:'pend'}}});d.rpc=()=>({maybeSingle:async()=>({data:{precio_final:1500.5},error:null})});const prev=global.fetch;let pref;global.fetch=async(url,opt)=>(pref=JSON.parse(opt.body),{ok:true,json:async()=>({init_point:'http://mock'})});try{const r=await new CompraFacilService(d).comprar('TEST','s',[{sku:'KG',cantidad:0.5}]);assert.equal(r.total,1501);assert.equal(pref.items[0].quantity,1);return {solicitadoKg:0.5,precioKg:1500.5,esperado:750.25,cobroPreparado:r.total,causa:'Compra Fácil redondea peso a entero y precio a pesos'};}finally{global.fetch=prev;}});
 const file='../../docs/auditoria-integral-2026-09-21/reproducciones.json';fs.writeFileSync(file,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));if(results.some(x=>!x.reproducido))process.exitCode=1;
})();
